---

- hosts: webservers
  user: that1guy15
  sudo: True

  vars:
    app_name: netmgmt
    repo_url: https://github.com/that1guy15/NetMgmt.git
    ntc_ansible_url: https://github.com/networktocode/ntc-ansible
    napalm_url: https://github.com/napalm-automation/napalm-ansible.git
    repo_remote: origin
    repo_version: master
    webapps_dir: /srv
    wsgi_file: wsgi.py
    wsgi_callable: app

  tasks:
    - name: ensure log directory
      action: file dest={{webapps_dir}}/{{app_name}}/log state=directory

    - name: deploy code from repository
      action: git repo={{repo_url}} dest={{webapps_dir}}/{{app_name}}/src remote={{repo_remote}} version={{repo_version}}

    - name: install dependencies into virtualenv
      action: pip requirements={{webapps_dir}}/{{app_name}}/src/requirements.txt virtualenv={{webapps_dir}}/{{app_name}}/venv state=present

    - name: create ansible library folder
      action: file {{webapps_dir}}/library state=directory owner=root

    - name: download ntc-ansible to library
      action: git repo={{ntc_ansible_url}} dest={{webapps_dir}}/{{app_name}}/library remote={{repo_remote}} version={{repo_version}} recursive=yes

    - name: install ntc-ansible
      command: python {{webapps_dir}}/{{app_name}}/library/setup.py install virtualenv={{webapps_dir}}/{{app_name}}/venv

    - name: download napalm to library
      action: git repo={{napalm_url}} dest={{webapps_dir}}/{{app_name}}/library remote={{repo_remote}} version={{repo_version}}

    - name: create supervisor program config
      action: template src=templates/supervisor.ini dest=/etc/supervisor/{{app_name}}.ini
      notify:
        - restart app

    - name: create nginx site config
      action: template src=templates/nginx_site.conf dest=/etc/nginx/sites-available/{{app_name}}.conf
      notify:
        - restart nginx

    - name: link nginx config
      action: file src=/etc/nginx/sites-available/{{app_name}}.conf dest=/etc/nginx/sites-enabled/{{app_name}}.conf state=link

    - name: restart supervisor program 
      service:
        name: supervisord
        state: restarted

    - name: restart nginx program 
      service:
        name: nginx
        state: restarted

    - name: start app
      action: supervisorctl name={{app_name}} state=started

  handlers:
    - name: restart app
      action: supervisorctl name={{app_name}} state=restarted

    - name: restart nginx
      action: service name=nginx state=restarted
